# Generated by Django 5.2.1 on 2025-06-02 17:03

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culture',
            name='actionneurs',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='capteurs',
        ),
        migrations.AlterModelOptions(
            name='alerte',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mesure',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='alerte',
            name='dashboard_a_type_pa_13fd02_idx',
        ),
        migrations.RemoveIndex(
            model_name='mesure',
            name='dashboard_m_culture_9da06c_idx',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='mesure',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='seuil_max',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='seuil_min',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='alerte',
            name='type_parametre',
        ),
        migrations.AddField(
            model_name='agriculteur',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='agriculteur',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerte',
            name='agriculteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='dashboard.agriculteur'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('humidity', 'Humidité'), ('ph', 'pH'), ('co2', 'CO2'), ('light', 'Lumière'), ('temperature', 'Température'), ('waterLevel', "Niveau d'eau")], default='humidity', max_length=20),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='culture',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='Actionneur',
        ),
        migrations.DeleteModel(
            name='Capteur',
        ),
    ]
